# Generated by Django 4.0.5 on 2022-06-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=3000)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('marked_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('count_in_stock', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(choices=[('AVAILABLE', 'Available'), ('OUT OF STOCK', 'Out of Stock')], max_length=250)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review', models.IntegerField(blank=True, null=True)),
                ('state', models.BooleanField(default=True, help_text='On makes item visible, off hides it')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product_category')),
            ],
        ),
    ]
