# Generated by Django 4.0.5 on 2022-06-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_title_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='alt_text',
            field=models.CharField(max_length=150),
        ),
    ]
