# Generated by Django 4.0.5 on 2022-06-11 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_description_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.TextField(choices=[('AVAILABLE', 'Available'), ('OUT OF STOCK', 'Out of Stock')], default='Available', max_length=250),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='alt_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
